### ISSUE TITLE
[PE-D][Tester D] Random table with no meaning at top of UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-4/tp#126]
![image.png](https://raw.githubusercontent.com/chongsun2002/ped/main/files/3022f0d3-5c2f-46a5-b987-7981e149bde4.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: chongsun2002/ped#2

**Comment by Peanuts359** [comment]
Will be fixed in the updated UG
