### ISSUE TITLE
[PE-D][Tester B] Name Field Fails Legitmate Non-Standard Names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-4/tp#146]
### What happens:
![image.png](https://raw.githubusercontent.com/Tkaixiang/ped/main/files/ae373f30-d452-483c-9953-3d70f6179e7a.png)

![image.png](https://raw.githubusercontent.com/Tkaixiang/ped/main/files/0124f3f9-05d4-4b5e-b679-f68a1fa9ac30.png)

- The name field does not allow for non-English non-standard names such as [Hyphenated Names](https://www.momjunction.com/articles/hyphenated-double-barrel-baby-names_00400945/)

### Environment:
- Windows 11

### Expected:
- The name field should be less restrictive and cater to unique names across the globe

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Tkaixiang/ped#10

**Comment by leowolf275** [comment]
Do we mention in the UG that our app only caters towards standard English names?!

**Comment by youngseopark05** [comment]
> Do we mention in the UG that our app only caters towards standard English names?!

I think we should (and change the person name to except hyphen).
