### ISSUE TITLE
[PE-D][Tester B] Lack of Ability to Edit Participant List of an Event

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-4/tp#164]
### What happens:

![image.png](https://raw.githubusercontent.com/Tkaixiang/ped/main/files/54807bf8-1519-46f3-ab45-f9c4bb68fe58.png)
- I am unable to edit the list of participants for an event without replacing the entire list of participants (i.e start from scratch), which is quite troublesome

### Expected:
- To be able to edit the participant list without having to replace the entire list

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Tkaixiang/ped#14

**Comment by youngseopark05** [comment]
This is a miscomm in the DG, but appending edits as a planned enhancements is also not a bad idea.
