### ISSUE TITLE
[PE-D][Tester A] User guide PDF file does not have functioning hyperlinks

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-4/tp#174]
**Description**
User guide PDF file was created by exporting from the github page displaying the UserGuide.md file.
This results in non-functional hyperlinks in the PDF file. A possible fix is to navigate to the web versions of the user guide, and export to PDF from that page.

**Screenshots**

![image.png](https://raw.githubusercontent.com/NicholasCWK/ped/main/files/83509712-61c8-4e91-9c28-a9f72cabbcad.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: NicholasCWK/ped#10

**Comment by Peanuts359** [comment]
hyperlinks will be added in the improved UG
