### ISSUE TITLE
[PE-D][Tester C] Developer Guide pdf is not user friendly

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-4/tp#179]
## Problem  

It is difficult to use the Developer Guide as it is in image form. Links cannot be clicked and Control F function cannot be used to search specific terms quickly.  This makes it difficult and not user friendly to use the Developer Guide.  

![image.png](https://raw.githubusercontent.com/accountexeregister/ped/main/files/55fd6b62-3325-47c6-89f9-5f0a7393a2ac.png)

## Suggestion  
Export the markdown to pdf instead of taking screenshots of the Developer Guide.  

-------------
Labels: `severity.High` `type.DocumentationBug`
original: accountexeregister/ped#11

**Comment by Peanuts359** [comment]
Will be fixed in updated DG
