### ISSUE TITLE
[PE-D][Tester C] User Guide not up-to-date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W14-4/tp#180]
## Problem
The User Guide is missing several elements, like adding person with different event specific roles such as r/referee and r/athlete. The command summary is also missing some commands, such as event related commands.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: accountexeregister/ped#12

**Comment by Peanuts359** [comment]
Will be fixed in the updated UG
