### ISSUE TITLE
Unable to determine a person's role in a specific event in the Person class

### ISSUE THREAD

**Issue by kaoxi998533** [AY2425S1-CS2103T-W14-4/tp#71]
Description:
In the current implementation of the Person class, a person's events and roles are stored separately in two Set collections (Set<Event> events and Set<Role> roles). However, there is no clear way to associate a specific role with a particular event.

For example, given the following fields in the Person class:

```java
private final Set<Event> events = new HashSet<>();
private final Set<Role> roles = new HashSet<>();
```
It is unclear which role the person plays in a given event since both events and roles are stored independently. This can make it difficult to track a person's participation in specific events.

Expected Behavior:
There should be a clear association between each event and the role the person plays in that event.

**Comment by youngseopark05** [comment]
Due to the changes in direction of the project, this doesn't appear to be an issue anymore, @kaoxi998533 if you agree please feel free to close the issue!
